import React from 'react';
import './hospital.css'; // Import the CSS file for styling

const Hospital = () => {
    const hospitals = [
      {
        name: "Chandpur General Hospital (PVT.)",
        rating: "3.2(6)",
        type: "Hospital",
        distance: "12.6 km",
        address: "Cumilla Rd",
        hours: "Open ⋅ Closes 11:30 PM",
        phone: "01711-033702",
        website: null,
      },
      {
        name: "Chandpur Medical College & Hospital",
        rating: "4.0(116)",
        type: "Hospital",
        distance: "13.8 km",
        address: "কবি নজরুল সড়ক",
        hours: "Open 24 hours",
        phone: "01827-150932",
        website: "Website",
      },
      {
        name: "২৫০ শয্যা বিশিষ্ট জেনারেল হাসপাতাল, চাঁদপুর",
        rating: "3.9(29)",
        type: "Government hospital",
        distance: "13.8 km",
        address: "6MF3+934, Kabi Nazrul Rd",
        hours: "Open 24 hours",
        phone: "01612-968241",
        website: null,
      },
      {
        name: "Central Hospital",
        rating: "4.4(20)",
        type: "Hospital",
        distance: "13.1 km",
        address: "6MG5+PHF, Shahid Muktijoddha Rd",
        hours: "Open 24 hours",
        phone: "01711-042907",
        website: null,
      },
      {
        name: "Chandpur City Hospital",
        rating: "3.0(4)",
        type: "Hospital",
        distance: "12.5 km",
        address: "6MJ7+9Q9, Stadium Rd",
        hours: "Open ⋅ Closes 9 PM",
        phone: "01902-248391",
        website: null,
      },
      {
        name: "Chandpur Al Amin Hospital",
        rating: "4.2(11)",
        type: "Hospital",
        distance: "12.9 km",
        address: "Horodoyal Rd",
        hours: "Open 24 hours",
        phone: "01710-102246",
        website: null,
      },
      {
        name: "Chandpur Diabetic Hospital",
        rating: "4.6(27)",
        type: "Hospital",
        distance: "12.0 km",
        address: "Comilla - Chandpur Hwy",
        hours: "Open 24 hours",
        phone: "01711-475971",
        website: null,
      },
      {
        name: "Bellevue Hospital",
        rating: "4.1(38)",
        type: "Hospital",
        distance: "11.9 km",
        address: "Dorji ghat BONGOBANDHU SHARAK",
        hours: "Open 24 hours",
        phone: "01711-159815",
        website: null,
      },
      {
        name: "Al Manar Hospital Private Ltd",
        rating: "2.9(17)",
        type: "Private hospital",
        distance: "12.6 km",
        address: "6MH7+5HG, Mission Rd",
        hours: "Open 24 hours",
        phone: "01761-964455",
        website: null,
      },
      {
        name: "Chandpur Medical Center",
        rating: "4.6(5)",
        type: "Hospital",
        distance: "11.8 km",
        address: "6MMC+M8F Chairman Ghat, Comilla - Chandpur Hwy",
        hours: "Open 24 hours",
        phone: "01784-580167",
        website: null,
      },
      {
        name: "Chandpur Modern Hospital (Pvt)",
        rating: "4.0(1)",
        type: "Hospital",
        distance: "12.2 km",
        address: "Bangabandu Rd",
        hours: "Open 24 hours",
        phone: "01747-586058",
        website: null,
      },
      {
        name: "Rainbow Hospital",
        rating: "4.1(21)",
        type: "Hospital",
        distance: "12.8 km",
        address: "652 Mission Rd",
        hours: "Open 24 hours",
        phone: "01715-511833",
        website: "Website",
      },
      {
        name: "Moon Hospital (Pvt)",
        rating: "3.5(12)",
        type: "Hospital",
        distance: "12.5 km",
        address: "Stadium Rd",
        hours: "Open 24 hours",
        phone: "01867-143464",
        website: null,
      },
      {
        name: "Disease of the Chest Clinic",
        rating: "4.1(19)",
        type: "Hospital",
        distance: "12.5 km",
        address: "6MH7+FQ8, Stadium Rd",
        hours: "Open ⋅ Closes 5 PM",
        phone: null,
        website: null,
      },
      {
        name: "Midland Hospital Private Ltd",
        rating: "4.1(12)",
        type: "Hospital",
        distance: "13.0 km",
        address: "6MF6+X2G, Haji Mohsin Rd",
        hours: "Open 24 hours",
        phone: "01712-633457",
        website: null,
      },
      {
        name: "Chandpur Adhunik Chokkhu Hashpatal (CACH)",
        rating: "4.7(12)",
        type: "Hospital",
        distance: "11.8 km",
        address: "Holding No 0280, Saudia City, Cumilla Rd",
        hours: "Open ⋅ Closes 8 PM",
        phone: "01779-194546",
        website: null,
      },
      {
        name: "Famous Specialized Hospital and Trauma Centre",
        rating: "4.7(6)",
        type: "Private hospital",
        distance: "12.0 km",
        address: "6MM9+9F2",
        hours: "Open 24 hours",
        phone: "01747-474719",
        website: "Website",
      },
      {
        name: "Mother & Child Care Hospital Private Ltd",
        rating: "3.7(6)",
        type: "Hospital",
        distance: "12.3 km",
        address: "6MH8+9HQ, Bangabandu Rd",
        hours: "Open 24 hours",
        phone: "01727-567316",
        website: null,
      },
      {
        name: "Karnofuli Hospital Chandpur",
        rating: "3.7(6)",
        type: "Hospital",
        distance: "12.8 km",
        address: "6MJ6+MG9, Unnamed Road",
        hours: "Open 24 hours",
        phone: "01869-708139",
        website: null,
      },
      {
        name: "Premier Hospital & Diagnostic Centre",
        rating: "4.1(11)",
        type: "Hospital",
        distance: "13.0 km",
        address: "6MF6+R3X, Haji Mohsin Rd",
        hours: "Open 24 hours",
        phone: "01963-911451",
        website: null,
      },
      {
        name: "General hospital",
        rating: "5.0(2)",
        type: "Hospital",
        distance: "13.8 km",
        address: "6MF3+67F",
        hours: "Open 24 hours",
        phone: null,
        website: null,
      },
      {
        name: "Al-Khidmah Medical Services (Pvt.), Chandpur",
        rating: "4.1(8)",
        type: "Medical diagnostic imaging center",
        distance: "12.5 km",
        address: "Stadium Rd",
        hours: "Open ⋅ Closes 10:30 PM",
        phone: "01718-294444",
        website: null,
      },
      {
        name: "Mazharul Haque BNSB Eye Hospital",
        rating: "4.3(23)",
        type: "Hospital",
        distance: "12.1 km",
        address: "Chandpur",
        hours: "Open ⋅ Closes 2 PM",
        phone: "01615-229122",
        website: "Website",
      },
      {
        name: "Barakah Hospital",
        rating: "4.0(3)",
        type: "Hospital",
        distance: "12.4 km",
        address: "6MM7+3P5, Stadium Rd",
        hours: "Open ⋅ Closes 10 PM",
        phone: "01841-404244",
        website: null,
      },
      {
        name: "Royal Hospital Private Ltd",
        rating: "4.3(3)",
        type: "Hospital",
        distance: "13.1 km",
        address: "6MH5+FH5, Haji Mohsin Rd",
        hours: "Open 24 hours",
        phone: "01874-675660",
        website: null,
      },
      {
        name: "Navana Hospital Private Ltd.",
        rating: "3.9(8)",
        type: "Hospital",
        distance: "12.5 km",
        address: "6MG8+C8C, Stadium Rd",
        hours: "Open 24 hours",
        phone: "01711-028880",
        website: null,
      },
      {
        name: "Chandpur MATS",
        rating: "3.3(3)",
        type: "Hospital",
        distance: "13.0 km",
        address: "Haji Mohsin Rd",
        hours: "Open ⋅ Closes 5:30 PM",
        phone: "01915-421911",
        website: null,
      },
      {
        name: "Crescent Hospital Private Ltd",
        rating: "5.0(1)",
        type: "Hospital",
        distance: "12.4 km",
        address: "6MM9+7F3, Road 4",
        hours: "Open ⋅ Closes 5 PM",
        phone: "01710-291032",
        website: null,
      },
      {
        name: "Bashundhara Hospital",
        rating: "4.0(1)",
        type: "Hospital",
        distance: "12.0 km",
        address: "6MM9+PFF",
        hours: "Open ⋅ Closes 9 PM",
        phone: "01718-450458",
        website: null,
      },
      {
        name: "Aalok Hospital-আলোক হাসপাতাল",
        rating: "No reviews",
        type: "Hospital",
        distance: "12.4 km",
        address: "Opposite of tax office, stadium road",
        hours: "Open 24 hours",
        phone: "01687-359607",
        website: null,
      },
      {
        name: "New Life Diagnostic Center Chandpur",
        rating: "4.3(11)",
        type: "Diagnostic center",
        distance: "13.3 km",
        address: "259 Cumilla Rd",
        hours: "Open ⋅ Closes 8 PM",
        phone: "01924-800145",
        website: "Website",
      },
      {
        name: "Mohona Diagnostic Centre",
        rating: "4.1(14)",
        type: "Diagnostic center",
        distance: "13.3 km",
        address: "6MG5+H2Q",
        hours: "Open ⋅ Closes 7 PM",
        phone: "01826-502426",
        website: null,
      },
      {
        name: "Dr. Lal pathlabs (Chandpur Healthcare)",
        rating: "No reviews",
        type: "Hospital",
        distance: "12.6 km",
        address: "6MJ7+R6G",
        hours: "Open 24 hours",
        phone: "01404-186551",
        website: null,
      },
      {
        name: "Abc",
        rating: "5.0(1)",
        type: "Fabric wholesaler",
        distance: "12.6 km",
        address: "Stadium Rd",
        hours: "Open ⋅ Closes 10:19 PM",
        phone: "01810-081988",
        website: null,
      },
      {
        name: "BAVS Chandpur Clinic",
        rating: "No reviews",
        type: "Hospital",
        distance: "11.8 km",
        address: "272 - kazi kanon, GT Road (Dokkhin), Chairman ghat",
        hours: "Open ⋅ Closes 5 PM",
        phone: "01825-762714",
        website: "Website",
      },
      {
        name: "FE ambulance service",
        rating: "5.0(1)",
        type: "Hospital",
        distance: "12.2 km",
        address: "6MQ8+W8V",
        hours: "Open 24 hours",
        phone: "01728-168626",
        website: null,
      },
      {
        name: "মা ও শিশু কল্যাণ কেন্দ্র চাঁদপুর",
        rating: "4.5(4)",
        type: "Hospital",
        distance: "13.6 km",
        address: "Unnamed Road",
        hours: "Open ⋅ Closes 5 PM",
        phone: "01745-058909",
        website: null,
      },
      {
        name: "C.V Hospital",
        rating: "No reviews",
        type: "Hospital",
        distance: "13.6 km",
        address: "6MG3+2V7, Chandpur, bashkhali",
        hours: "Open ⋅ Closes 8 PM",
        phone: "01873-565067",
        website: null,
      },
    ];

  return (
    <div className="hospital-container">
      <h1 className="hospital-header">Hospitals in Chandpur</h1>
      <table className="hospital-table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Address</th>
            <th>Hours</th>
            <th>Phone</th>
            <th>Website</th>
          </tr>
        </thead>
        <tbody>
          {hospitals.map((hospital, index) => (
            <tr key={index}>
              <td>{hospital.name}</td>
              
              <td>{hospital.address}</td>
              <td>{hospital.hours}</td>
              <td>{hospital.phone}</td>
              <td>
                {hospital.website ? (
                  <a href="#">{hospital.website}</a>
                ) : (
                  'N/A'
                )}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default Hospital;
